/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JisajiliRouteImport } from './routes/jisajili'
import { Route as LipaRouteImport } from './routes/lipa'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminLoginRouteImport } from './routes/admin.login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JisajiliRoute = JisajiliRouteImport.update({
  id: '/jisajili',
  path: '/jisajili',
  getParentRoute: () => rootRouteImport,
} as any)
const LipaRoute = LipaRouteImport.update({
  id: '/lipa',
  path: '/lipa',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/jisajili': typeof JisajiliRoute
  '/lipa': typeof LipaRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof DashboardRoute
  '/admin': typeof AdminRoute
  '/admin/login': typeof AdminLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/jisajili': typeof JisajiliRoute
  '/lipa': typeof LipaRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof DashboardRoute
  '/admin': typeof AdminRoute
  '/admin/login': typeof AdminLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/jisajili': typeof JisajiliRoute
  '/lipa': typeof LipaRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof DashboardRoute
  '/admin': typeof AdminRoute
  '/admin/login': typeof AdminLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/jisajili' | '/lipa' | '/login' | '/dashboard' | '/admin' | '/admin/login'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/jisajili' | '/lipa' | '/login' | '/dashboard' | '/admin' | '/admin/login'
  id: '__root__' | '/' | '/jisajili' | '/lipa' | '/login' | '/dashboard' | '/admin' | '/admin/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JisajiliRoute: typeof JisajiliRoute
  LipaRoute: typeof LipaRoute
  LoginRoute: typeof LoginRoute
  DashboardRoute: typeof DashboardRoute
  AdminRoute: typeof AdminRoute
  AdminLoginRoute: typeof AdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jisajili': {
      id: '/jisajili'
      path: '/jisajili'
      fullPath: '/jisajili'
      preLoaderRoute: typeof JisajiliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lipa': {
      id: '/lipa'
      path: '/lipa'
      fullPath: '/lipa'
      preLoaderRoute: typeof LipaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JisajiliRoute: JisajiliRoute,
  LipaRoute: LipaRoute,
  LoginRoute: LoginRoute,
  DashboardRoute: DashboardRoute,
  AdminRoute: AdminRoute,
  AdminLoginRoute: AdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
